name: infra-azure-main
trigger:
  tags:
    include:
    - '*'
  branches:
    exclude:
    - '*'
pool: selfhostedlinux
variables:
- group: ci-auth
stages:
- stage: Plan
  jobs:
    - job: plan
      displayName: Plan Infrastructure
      container: dousvies/ci-terraform:azure
      steps:
      - bash: |
          export ARM_CLIENT_ID=$(client_id)
          export ARM_CLIENT_SECRET=$(client_secret)
          export ARM_SUBSCRIPTION_ID=$(subscription_id)
          export ARM_TENANT_ID=$(tenant_id)
          terraform init
          terraform plan -out=tfplan
